service: default
runtime: nodejs20
instance_class: F1
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: "301"
  - url: .*
    script: auto
  - url: /assets
    static_dir: /assets
    expiration: "0d 0h"
    http_headers:
      cache-control: public, max-age=100
      Cache-Control: public, max-age=100
